version: '3'
services:
  mongo:
    image: mongo:5
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: ticket
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:

