// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/AppButton.vue')['default']
    BarChart: typeof import('./src/components/BarChart.vue')['default']
    Base: typeof import('./src/components/TicketCard/Base.vue')['default']
    copy: typeof import('./src/components/TicketCard/SaleTicket copy.vue')['default']
    EclipseSpinner: typeof import('./src/components/EclipseSpinner.vue')['default']
    ElipseSpinner: typeof import('./src/components/ElipseSpinner.vue')['default']
    LineChart: typeof import('./src/components/LineChart.vue')['default']
    MyTicket: typeof import('./src/components/TicketCard/MyTicket.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sale: typeof import('./src/components/TicketCard/Sale.vue')['default']
    SaleTicket: typeof import('./src/components/TicketCard/SaleTicket.vue')['default']
    SectionBlock: typeof import('./src/components/SectionBlock.vue')['default']
    Ticket: typeof import('./src/components/Ticket.vue')['default']
    TicketCard: typeof import('./src/components/TicketCard/index.vue')['default']
  }
}
